### ISSUE TITLE
Some tests do not build, some crash on 1.7.1 and latest 1.x

### ISSUE THREAD

**Issue by asahtik** [Matroska-Org/libmatroska#176]
Build of some tests fails (ran on Fedora 39 and Ubuntu 22.04).

`mux/test6.cpp` aborts when ran. Tested with 1.7.1 and latest 1.x.

GDB output:
```
Creating "muxed.mkv"
test6: /builddir/build/BUILD/libmatroska-1.7.1/src/KaxSemantic.cpp:931: virtual filepos_t libmatroska::KaxContentSigAlgo::RenderData(libebml::IOCallback&, bool, bool): Assertion `false' failed.

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
```

Trace:
```
#5  0x00007ffff7973c57 in __assert_fail (assertion=0x7ffff7f5f84d "false",
    file=0x7ffff7f62698 "/builddir/build/BUILD/libmatroska-1.7.1/src/KaxSemantic.cpp", line=931,
    function=0x7ffff7f633a0 "virtual filepos_t libmatroska::KaxContentSigAlgo::RenderData(libebml::IOCallback&, bool, bool)") at assert.c:101
#6  0x00007ffff7f542c7 in libmatroska::KaxContentSigAlgo::RenderData (this=<optimized out>)
    at /usr/src/debug/libmatroska-1.7.1-4.fc39.x86_64/src/KaxSemantic.cpp:931
#7  0x00007ffff7ec9086 in libebml::EbmlElement::Render (this=0x421e20, output=..., bWithDefault=false, bKeepPosition=false,
    bForceRender=false) at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlElement.cpp:597
#8  0x00007ffff7ecadae in libebml::EbmlMaster::RenderData (this=0x421c40, output=..., bForceRender=false, bWithDefault=false)
    at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlMaster.cpp:100
#9  0x00007ffff7ec9086 in libebml::EbmlElement::Render (this=0x421c40, output=..., bWithDefault=false, bKeepPosition=false,
    bForceRender=false) at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlElement.cpp:597
#10 0x00007ffff7ecadae in libebml::EbmlMaster::RenderData (this=0x4218e0, output=..., bForceRender=false, bWithDefault=false)
    at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlMaster.cpp:100
#11 0x00007ffff7ec9086 in libebml::EbmlElement::Render (this=0x4218e0, output=..., bWithDefault=false, bKeepPosition=false,
    bForceRender=false) at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlElement.cpp:597
#12 0x00007ffff7ecadae in libebml::EbmlMaster::RenderData (this=0x421830, output=..., bForceRender=false, bWithDefault=false)
    at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlMaster.cpp:100
#13 0x00007ffff7ec9086 in libebml::EbmlElement::Render (this=0x421830, output=..., bWithDefault=false, bKeepPosition=false,
    bForceRender=false) at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlElement.cpp:597
#14 0x00007ffff7ecadae in libebml::EbmlMaster::RenderData (this=0x421190, output=..., bForceRender=false, bWithDefault=false)
    at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlMaster.cpp:100
#15 0x00007ffff7ec9086 in libebml::EbmlElement::Render (this=0x421190, output=..., bWithDefault=false, bKeepPosition=false,
    bForceRender=false) at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlElement.cpp:597
#16 0x00007ffff7ecadae in libebml::EbmlMaster::RenderData (this=0x420bd0, output=..., bForceRender=false, bWithDefault=false)
    at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlMaster.cpp:100
#17 0x00007ffff7ec9086 in libebml::EbmlElement::Render (this=0x420bd0, output=..., bWithDefault=false, bKeepPosition=false,
    bForceRender=false) at /home/work/.hunter/_Base/cb0ea1f/187c4c7/461adde/Build/EBML/Source/src/EbmlElement.cpp:597
#18 0x0000000000404d80 in main (argc=1, argv=0x7fffffffd868) at /home/work/workspaces/lib/libmatroska/test/mux/test6.cpp:203
```

**Comment by moratom** [comment]
I have the same issue.
